spring:
  application:
    name: eureka-server
  boot:
    admin:
      url: http://admin_server

eureka:
  instance:
    hostname: eureka_server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka_server/eureka/

management:
  security:
    enabled: false

security:
  basic:
    enabled: false

endpoints:
 shutdown:
  enabled: true